name: Flatpak

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: io.github.catoblepa.signature-viewer.json
          bundle: io.github.catoblepa.signature-viewer.flatpak
          cache: true
          cache-key: flatpak-builder-${{ hashFiles('io.github.catoblepa.signature-viewer.json') }}
          upload-artifact: false

      - name: Upload bundle as artifact
        uses: actions/upload-artifact@v7
        with:
          name: io.github.catoblepa.signature-viewer.flatpak
          path: io.github.catoblepa.signature-viewer.flatpak
          if-no-files-found: error

      - name: Publish to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v3
        with:
          files: io.github.catoblepa.signature-viewer.flatpak
